name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 临时解决 Node.js 警告
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config cmake ninja-build

      - name: Install buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 Cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wxrobot-apk
          path: bin/*.apk
